### PR TITLE
Addign Dropdown Menu In components

### PR DESCRIPTION
**Pull request by usmanajaz**
Adding a drop company in components and taking the feedback received by Lisa and implementing in that into table component designed by me early on

### CODE REVIEW

**Comment by doubleedesign** [comment]
@usmanajaz Could you please separate these out into one pull request for each individual component? This makes them easier to review and progress each as an item of work.

**Comment by usmanajaz** [comment]
i think i cant process into two requests i had to close the first one to place the second one first one is in closed section

**Comment by doubleedesign** [comment]
> i think i cant process into two requests i had to close the first one to place the second one first one is in closed section

You can work on multiple pull requests by having one branch per PR in your repository fork.

**Comment by doubleedesign** [comment]
Closed due to the student not being in the web dev team anymore.

**Pull request closed without merging**
